/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SettlementPaymentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkPayment"
      | "getRecipient"
      | "getSettlementFee"
      | "isJobPaid"
      | "owner"
      | "paidJobs"
      | "payForSettlement"
      | "paymentAmounts"
      | "recipient"
      | "setRecipient"
      | "setSettlementFee"
      | "settlementFee"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FeeUpdated" | "RecipientUpdated" | "SettlementPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkPayment",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSettlementFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isJobPaid", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paidJobs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "payForSettlement",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentAmounts",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "recipient", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlementFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettlementFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isJobPaid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paidJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payForSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recipient", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlementFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipientUpdatedEvent {
  export type InputTuple = [
    oldRecipient: AddressLike,
    newRecipient: AddressLike
  ];
  export type OutputTuple = [oldRecipient: string, newRecipient: string];
  export interface OutputObject {
    oldRecipient: string;
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementPaidEvent {
  export type InputTuple = [
    jobId: BytesLike,
    payer: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    payer: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    jobId: string;
    payer: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SettlementPayment extends BaseContract {
  connect(runner?: ContractRunner | null): SettlementPayment;
  waitForDeployment(): Promise<this>;

  interface: SettlementPaymentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkPayment: TypedContractMethod<
    [jobId: string],
    [
      [boolean, string, bigint] & {
        isPaid: boolean;
        payer: string;
        amount: bigint;
      }
    ],
    "view"
  >;

  getRecipient: TypedContractMethod<[], [string], "view">;

  getSettlementFee: TypedContractMethod<[], [bigint], "view">;

  isJobPaid: TypedContractMethod<[jobId: string], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paidJobs: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  payForSettlement: TypedContractMethod<[jobId: string], [void], "payable">;

  paymentAmounts: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  recipient: TypedContractMethod<[], [string], "view">;

  setRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setSettlementFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  settlementFee: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkPayment"
  ): TypedContractMethod<
    [jobId: string],
    [
      [boolean, string, bigint] & {
        isPaid: boolean;
        payer: string;
        amount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSettlementFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isJobPaid"
  ): TypedContractMethod<[jobId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paidJobs"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "payForSettlement"
  ): TypedContractMethod<[jobId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "paymentAmounts"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSettlementFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlementFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RecipientUpdated"
  ): TypedContractEvent<
    RecipientUpdatedEvent.InputTuple,
    RecipientUpdatedEvent.OutputTuple,
    RecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementPaid"
  ): TypedContractEvent<
    SettlementPaidEvent.InputTuple,
    SettlementPaidEvent.OutputTuple,
    SettlementPaidEvent.OutputObject
  >;

  filters: {
    "FeeUpdated(uint256,uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "RecipientUpdated(address,address)": TypedContractEvent<
      RecipientUpdatedEvent.InputTuple,
      RecipientUpdatedEvent.OutputTuple,
      RecipientUpdatedEvent.OutputObject
    >;
    RecipientUpdated: TypedContractEvent<
      RecipientUpdatedEvent.InputTuple,
      RecipientUpdatedEvent.OutputTuple,
      RecipientUpdatedEvent.OutputObject
    >;

    "SettlementPaid(bytes32,address,uint256,uint256)": TypedContractEvent<
      SettlementPaidEvent.InputTuple,
      SettlementPaidEvent.OutputTuple,
      SettlementPaidEvent.OutputObject
    >;
    SettlementPaid: TypedContractEvent<
      SettlementPaidEvent.InputTuple,
      SettlementPaidEvent.OutputTuple,
      SettlementPaidEvent.OutputObject
    >;
  };
}
